# Generated by Django 5.2.7 on 2025-11-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkcategory',
            name='color',
            field=models.CharField(default='#0d6efd', help_text='Hex color for category (e.g., #0d6efd)', max_length=7),
        ),
    ]
