# Generated by Django 5.2.7 on 2025-11-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_linkcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon_class',
            field=models.CharField(default='fas fa-link', help_text='Font Awesome icon class', max_length=100),
        ),
    ]
