# Generated by Django 5.2.7 on 2025-11-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon_class',
            field=models.CharField(default='fas fa-link', help_text='Font Awesome icon class. <a href="https://fontawesome.com/icons?d=gallery&m=free" target="_blank">Browse icons</a>', max_length=100),
        ),
    ]
