# Generated by Django 5.2.7 on 2025-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_link_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='authenticated_only',
            field=models.BooleanField(default=False, help_text='Only show this link to authenticated users'),
        ),
    ]
