# Generated by Django 5.2.7 on 2025-11-26 11:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_link_authenticated_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
